name: Build PyQt App Installer

on:
  push:
    branches:
      - main  # 只在 main 分支推送时触发
    tags:
      - 'v*.*.*'  # 匹配版本标签，比如 v1.0.0

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 获取代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 设置 Python 版本为 3.10

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip  # 更新 pip
        pip install -r requirements.txt  # 安装依赖

    - name: Install Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"  # 下载 Inno Setup
        Start-Process .\is.exe /VERYSILENT -Wait  # 安静安装 Inno Setup

    - name: 获取版本号
      id: version
      run: |
        # 从 Git 标签中提取版本号（例如 v1.0.0 -> 1.0.0）
        VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\/v\(.*\)/\1/')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV  # 将版本号存入环境变量

    - name: 使用 PyInstaller 构建应用
      run: |
        # 使用版本号来命名构建的应用
        python -m PyInstaller --name MyApp-${{ env.VERSION }} --onefile --noconsole --icon=resources\app.ico main.py

    - name: 使用 Inno Setup 构建安装包
      run: |
        # 更新 Inno Setup 脚本中的应用名为带版本号的形式
        sed -i "s/MyApp/MyApp-${{ env.VERSION }}/" installer.iss
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss  # 使用 Inno Setup 生成安装包

    - name: 上传安装包到 GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        # 使用版本号作为 GitHub Release 的标签
        tag_name: v${{ env.VERSION }}
        # 上传生成的安装包，文件名带版本号
        files: output/MyApp-${{ env.VERSION }}.exe
        prerelease: true  # 标记为预发布版本
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # 使用 GitHub Personal Access Token 进行认证

