name: Build PyQt App Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process .\is.exe /VERYSILENT -Wait

    - name: Build with PyInstaller
      run: |
        pyinstaller --name MyApp --onefile --noconsole --icon=resources\app.ico main.py

    - name: Build installer with Inno Setup
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload installer to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: output\HelloPyQtInstaller.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
